apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: openliberty-daytrader-git
    app.kubernetes.io/component: openliberty-daytrader-git
    app.kubernetes.io/instance: openliberty-daytrader-git
    app.kubernetes.io/name: openliberty-daytrader-git
    app.kubernetes.io/part-of: openliberty-daytrader-app
  name: openliberty-daytrader-git
spec:
  lookupPolicy:
    local: false
